# Generated by Django 3.2 on 2023-08-31 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('num_seasons', models.PositiveIntegerField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='tvshow_previews/')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='tvshow_videos/')),
                ('genres', models.ManyToManyField(to='serial.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='episodes/')),
                ('episode_number', models.PositiveIntegerField()),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serial.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serial.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
